### ISSUE TITLE
.ts file error

### ISSUE THREAD

**Issue by eson57** [michaeljohnbarrett/harbour-quaycentral#2]
Trying to translate QuayCentral into Swedish I get this error message from Qt Linguist...
`Unexpected tag at harbour-quaycentral.ts:242:19`
...and I'm not skilled enough to figure out what is wrong. Qt Linguist can't open file because of this error.

**Comment by mjebdev** [comment]
Thanks for bringing this to my attention. I'd neglected to deal with the html characters included as part of a link in one of the strings. It was also a duplicate so I just removed it as the original had the correct formatting for the tags. I haven't used Qt Linguist before today but it appeared to open normally for me, so it should be good to go.

**Comment by eson57** [comment]
Thanks! Looks OK now.
